[Add]: Unit test of model and VM, also IntegrationTest of VM
Coding-Pit-Dev/PVPC-iOS pull request #10
Opened 2024-08-25 08:12 UTC by Popitus

Add a Basic Test (Unit Test & Integration Test) to project and merge with develop to check GitHub Actions

2024-09-01 09:04 UTC, juanjecilla requested changes
@Popitus separa los steps de la action para que los test unitarios se hagan en un step y los de integración en otro.

2024-09-04 09:38 UTC, juanjecilla requested changes

2024-09-04 09:38 UTC, juanjecilla commented on PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest.swift
> +        XCTAssertNotEqual(prices, sut?.prices,"Deberia haber datos dentro de la lista")
Los textos tienen que estar en inglés.

2024-09-04 09:38 UTC, juanjecilla commented on PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest.swift
> +
Intenta quitar estos espacios innecesarios. No lo detecta SwiftLint?

2024-09-05 07:37 UTC, Popitus commented on PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest.swift
> +        XCTAssertNotEqual(prices, sut?.prices,"Deberia haber datos dentro de la lista")
Correcto, los voy cambiando

2024-09-05 07:38 UTC, Popitus commented on PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest.swift
> +
Estan separados como Arrange - Act - Assert, pero sin los comentarios

2024-09-05 07:45 UTC, juanjecilla commented
Me refiero a los extras del final.

El jue, 5 sept 2024 9:38, Oliver R.C. ***@***.***> escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest.swift
> <https://github.com/Coding-Pit-Dev/PVPC-iOS/pull/10#discussion_r1744965151>
> :
>
> > +
> +    }
> +
> +    func testGetPricesListUpdate() async throws {
> +        shouldReturnError = false
> +
> +        await sut?.getPricesList()
> +        let firstPrices = sut?.prices
> +
> +        numberOfJson = 2
> +        await sut?.getPricesList()
> +
> +        let expectedPrices = sut?.prices
> +
> +        XCTAssertNotEqual(firstPrices, expectedPrices ,"Los datos no deben ser iguales")
> +
>
> Estan separados como Arrange - Act - Assert, pero sin los comentarios
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Coding-Pit-Dev/PVPC-iOS/pull/10#discussion_r1744965151>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7SC4ZN4HHGOMYIGEFADQ3ZVAC77AVCNFSM6AAAAABNCKMXG6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEOBSGEYDONZTG4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-09-05 07:52 UTC, Popitus commented on PVPCPlannerTests/IntegrationTest/PriceVMIntegrationTest.swift
> +
Entendido.

2024-09-05 07:53 UTC, Popitus commented
Meto dentro del Ci el check de lint?
para poder asi cerrar la rama?

2024-09-05 08:19 UTC, juanjecilla approved these changes

2024-09-05 08:32 UTC, merged