Feature/local data source: Added the localDataSource with tests
Coding-Pit-Dev/PVPC-iOS pull request #12
Opened 2024-09-18 15:20 UTC by mriaus

## Descripción de los cambios
---
Añadidos los casos de uso para guardar datos en local 

### Finalidad de la PR
---
 
- [ ] 🐛 (Bug)
- [X] 🧑🏻‍💻 (Feature)
- [ ] 🌶️ (Hotfix)

### Tipo de cambio
---
 
- [ ] Corrección de errores 
- [X] Nueva característica
- [ ] Mejora 
- [ ] Refactorización 
- [ ] Documentación 
- [ ] Otros

### Checklist
---

 

- [ ] He seguido las directrices del código.
- [X] He realizado una revisión de código local.
- [X] He ejecutado las pruebas y todas pasan.
- [X] He añadido pruebas que prueban mis cambios.
- [ ] He actualizado la documentación si es necesario.

### Cómo probar los cambios
--- Para probarlo se pueden usar los test o habría que implementarlo junto a la obtención de los datos
### Capturas de pantalla (si crees que es necesario)
---
### Notas adicionales
---
Nada que añadir

### URL de la tarea
---
[Tarea](https://app.clickup.com/t/86bzhqcfj)

2024-09-18 16:26 UTC, juanjecilla requested changes
Revisa lo de los espacios. @Popitus también que de su opinión cuando pueda.

2024-09-18 16:26 UTC, juanjecilla commented on PVPCPlanner/Domain/UseCases/AddPVPCToLocaDBUseCase.swift
> +    // TODO: See how to refactor this, repeated in all the useCaseWith SwiftData
Si ponemos un TODO: hay que abrir una tarea en clickup y poner el enlace aquí.

2024-09-18 16:26 UTC, juanjecilla commented on PVPCPlanner/Domain/UseCases/AddPVPCToLocaDBUseCase.swift
> +    private var  databaseContainer = PVPCDatabaseContainer.shared.container
Aquí hay un espacio extra, has usado el linter que ha configurado oli?

2024-09-18 16:26 UTC, juanjecilla commented on PVPCPlanner/Domain/UseCases/GetAllPVPCFromLocalDBUseCase.swift
> +    private var  databaseContainer = PVPCDatabaseContainer.shared.container
Espacio extra.

2024-09-18 16:26 UTC, juanjecilla commented on PVPCPlanner/Domain/UseCases/GetAllPVPCFromLocalDBUseCase.swift
> +
Espacio extra.

2024-09-18 16:37 UTC, Popitus commented on PVPCPlannerTests/UnitTests/AddPVPCToLocaDBUseCaseTest.swift
> +
Si no se usa eliminar el teardown....

2024-09-18 16:37 UTC, Popitus commented on PVPCPlannerTests/UnitTests/GetAllPVPCFromLocalDBUseCaseTest.swift
> +
Si no se usa eliminar el teardown...

2024-09-18 16:39 UTC, Popitus commented on PVPCPlanner/DTO/PVPCModelLocal.swift
> +
Eliminar estos encabezados..

2024-09-18 16:39 UTC, Popitus commented on PVPCPlanner/Data/DBContainers/PVPCDatabaseContainer.swift
> +
Eliminar estos comentarios

2024-09-23 08:39 UTC, Popitus approved these changes, later dismissed

2024-09-23 10:06 UTC, juanjecilla commented on PVPCPlanner/App/PVPCPlannerApp.swift
> +import SwiftData
Este import es necesario?

2024-09-23 10:06 UTC, juanjecilla commented on PVPCPlanner/Data/DBContainers/PVPCDatabaseContainer.swift
> +enum PVPCDatabaseError: Error {
Este enum sácalo a un fichero distinto

2024-09-23 10:46 UTC, Popitus commented on PVPCPlanner/App/PVPCPlannerApp.swift
> +import SwiftData
No, por ahora aquí no

2024-09-23 11:15 UTC, mriaus commented on PVPCPlanner/Data/DBContainers/PVPCDatabaseContainer.swift
> +enum PVPCDatabaseError: Error {
Donde debería poner esta clase de ficheros? En data? Yo es que siempre los he puesto en un fichero de utils cuando los he puesto aparte, pero entiendo que no es lo mejor

2024-09-23 13:11 UTC, juanjecilla commented on PVPCPlanner/Data/DBContainers/PVPCDatabaseContainer.swift
> +enum PVPCDatabaseError: Error {
Si esto sólo se está usando aquí, dejalo en el mismo paquete de momento. Si luego se usa en otros sitios, habrá que moverlo a donde tenga sentido.

2024-09-23 13:11 UTC, juanjecilla commented on PVPCPlanner/App/PVPCPlannerApp.swift
> +import SwiftData
Pos a quitarlo.

2024-09-25 18:07 UTC, juanjecilla approved these changes

2024-09-25 18:23 UTC, merged