Feature/show prize component
Coding-Pit-Dev/PVPC-iOS pull request #18
Opened 2024-11-03 12:02 UTC by mriaus

## Descripción de los cambios
---
(Añade aquí tu descripción)

### Finalidad de la PR
---
 
- [ ] 🐛 (Bug)
- [X] 🧑🏻‍💻 (Feature)
- [ ] 🌶️ (Hotfix)

### Tipo de cambio
---
 
- [ ] Corrección de errores 
- [X] Nueva característica
- [ ] Mejora 
- [ ] Refactorización 
- [ ] Documentación 
- [ ] Otros

### Checklist
---

 

- [X] He seguido las directrices del código.
- [X] He realizado una revisión de código local.
- [ ] He ejecutado las pruebas y todas pasan.
- [ ] He añadido pruebas que prueban mis cambios.
- [X] He actualizado la documentación si es necesario.

### Cómo probar los cambios
---
### Capturas de pantalla (si crees que es necesario)
---
![imagen](https://github.com/user-attachments/assets/46fdebe0-cb31-4a9c-aa90-c2488fb30c0a)
<img width="244" alt="Captura de pantalla 2024-11-03 a las 12 09 56" src="https://github.com/user-attachments/assets/05b0d76d-3837-4f2a-8fa2-1e03d1b96738">

### Notas adicionales
---
Nada que añadir

### URL de la tarea
---
[(Añade aquí tu tarea)](https://app.clickup.com/t/86bzhqcff)

2024-11-07 12:50 UTC, juanjecilla requested changes
Faltan tests también

2024-11-07 12:50 UTC, juanjecilla commented on PVPCPlanner/Utils/Extensions/PVPCModel+Extension.swift
> +// MARK: Use example
Estos comentarios hacen falta?

2024-11-07 12:50 UTC, juanjecilla commented on PVPCPlanner/Utils/Extensions/PVPCModel+Extension.swift
> +        // Gets the price
Este comentario hace referencia a algo que se entiende ya a través del nombre del método.

2024-11-07 12:50 UTC, juanjecilla commented on PVPCPlanner/Utils/PricesCardHelpers.swift
> +            case ..<0.10:
Saca estos números a constantes.

2024-11-07 12:50 UTC, juanjecilla commented on PVPCPlanner/Utils/PricesCardHelpers.swift
> +    case cym
Se le pueden dar otros nombres que sean más definitorios.

2024-11-09 17:40 UTC, mriaus commented on PVPCPlanner/Utils/Extensions/PVPCModel+Extension.swift
> +// MARK: Use example
Me parecia buena idea tenerlos como Mark, ya que se ven resaltados en el minimapa del ide y por si se necesitara mas adelante en algunos componentes complejos ejemplos de uso me parecia una buena idea, se ve algo así:
![imagen](https://github.com/user-attachments/assets/2bb0d542-93ca-4994-b65d-cc71bfaa1966)

Pero pueden quitarse, como os parezca

2024-11-09 21:42 UTC, juanjecilla requested changes

2024-11-09 21:42 UTC, juanjecilla commented on PVPCPlanner/Utils/Extensions/PVPCModel+Extension.swift
> +// MARK: Use example
Mmmm yo no lo dejaría porque al final es una especie de docu y el código no es el mejor sitio para dejarlo.

2024-11-09 21:42 UTC, juanjecilla commented on PVPCPlanner/Presentation/PVPCModel.swift
> +    // Precio Península, Canarias, Baleares
En vez de poner el comentario, cambia a un nombre que sea más definitorio.

2024-11-09 21:42 UTC, juanjecilla commented on PVPCPlanner/View/Components/CustomCardComponent.swift
> +    var backgroundColor: Color? = Color.white
Necesitamos que sea nulable?

2024-11-09 21:42 UTC, juanjecilla commented on PVPCPlanner/View/Components/PricesCard.swift
> +                Text(pvpcModel.price + "€")
Saca esto a un string aparte para que se pueda gestionar todo desde el mismo sitio.

2024-11-09 21:42 UTC, juanjecilla commented on PVPCPlannerTests/UnitTests/PricesCardHelpersTest.swift
> +
Espacio extra.

2024-11-10 16:34 UTC, mriaus commented on PVPCPlanner/View/Components/CustomCardComponent.swift
> +    var backgroundColor: Color? = Color.white
Lo ponía opcional para que no fuera un parametro obligatorio si queriamos dejarlo por defecto, alomejor se puede gestionar de otra manera, siempre lo he visto así

2024-11-10 17:28 UTC, juanjecilla commented
Me parece bien pero si para este caso concreto siempre tiene un color, no
tendría sentido que fuera opcional.

El dom, 10 nov 2024 17:34, mriaus ***@***.***> escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In PVPCPlanner/View/Components/CustomCardComponent.swift
> <https://github.com/Coding-Pit-Dev/PVPC-iOS/pull/18#discussion_r1835735442>
> :
>
> > @@ -3,11 +3,14 @@ import SwiftUI
>  struct CustomCardComponent<BodyContent: View, FooterContent: View>: View {
>      var bodyContent: BodyContent
>      var footerContent: FooterContent?
> -
> +    var backgroundColor: Color? = Color.white
>
> Lo ponía opcional para que no fuera un parametro obligatorio si queriamos
> dejarlo por defecto, alomejor se puede gestionar de otra manera, siempre lo
> he visto así
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Coding-Pit-Dev/PVPC-iOS/pull/18#discussion_r1835735442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7SC465AWHCU7XJJHIDNRLZ76DK3AVCNFSM6AAAAABRCVKAJWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRVHAYDCNBVHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-11-10 17:29 UTC, mriaus commented on PVPCPlanner/View/Components/PricesCard.swift
> +                Text(pvpcModel.price + "€")
No se si es exactamente lo que me pedias, pero he añadido un fichero de traducciones que pilla la variable y el simbolo y he cambiado como estaba el texto, subo el cambio así y me comentas si no

2024-11-10 18:17 UTC, juanjecilla approved these changes

2024-11-10 18:17 UTC, juanjecilla commented on PVPCPlanner/Presentation/PVPCModel.swift
> +    let priceMainlandAndIslands: String
Mucho mejor.

2024-11-10 18:18 UTC, juanjecilla commented on PVPCPlanner/View/Components/PricesCard.swift
> +                Text(pvpcModel.price + "€")
Sip, el fichero este que has creado para que si luego hacemos más idiomas, no haya que cambiar nada en el código.

2024-11-10 18:39 UTC, merged